---
- hosts: webserver
  become: yes
  tasks:
  - name: update packages for Debian
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
  - name: install apache for Debain
    apt:
      name: apache2
      state: present
    notify:
    - Restart Apache2
    when: ansible_os_family =="Debian"
  - name: install apache for RedHat
    yum:
      name: httpd
      state: present
    notify:
    - Restart Httpd
    when: ansible_os_family == "RedHat"
  - name: Create the home page
    copy:
      dest: /var/www/html/index.html
      content: "<h1> Welcome To Apache (Controlled By Ansible) </h1>"
    #notify:
    #- Restart Apache
  handlers:
  - name: Restart Apache2
    service:
      name: apache2
      state: restarted
  - name: Restart Httpd
    service:
      name: httpd
      state: restarted

